Publishpress Authors to Authorship WP CLI command
humanmade/authorship pull request #101
Opened 2022-05-30 16:18 UTC by tomjn

Adds an initial WP CLI command and a subcommand for migrating from PPA to Authorship

Closes #100

2022-05-30 19:37 UTC, tomjn commented
Things that I think should happen:

 - a code review from another HM engineer
 - specifying post type support
 - ability to specify a specific post with an overwrite
 - pass through other arguments to the `get_posts` args ( perhaps this is how post types are supported )
 - a subcommand to erase authorship data on a post or posts?
 - better dry run reporting

I don't expect all of these to happen here though, but I'm going to prioritise a code review and what I need for the specific use case at hand

2022-06-01 09:01 UTC, svandragt submitted a review, later dismissed
Left some feedback for your consideration

2022-06-01 09:01 UTC, svandragt commented on inc/cli/class-commands.php
> +	private function get_ppa_user_id( WP_Term $ppa_author, bool $dry_run ) : int {
It's unexpected that a `get_*` function creates anything, let alone users. I'd recommend to default to false, update PHPDoc and rename the function to something else such as `ensure_ppa_user` as a creation function would be expected to return an id of the created object?

```suggestion
	private function get_ppa_user_id( WP_Term $ppa_author, bool $create_users = false ) : int {
```

2022-06-01 10:08 UTC, tomjn commented on README.md
> +wp authorship migrate_ppa --dry-run=true
That makes sense, perhaps `wp authorship migrate ppa`?

2022-06-13 07:53 UTC, shadyvb requested changes
Looks okay generally. Just one observation, that this iterates over ALL posts, rather than targeting those _with_ PPA data and _without_ authorship data, unsure if there is some context to doing that, but it'd not be super nice on large installations. Running time can be drastically improved if we did the filtering in the query rather than after. ( and even substantially faster if we went lower level as in the [original command](https://cs.github.com/humanmade/siemens-ingenuity/blob/154b8d6477ececb5336aeed71a72c51a68a30142/content/plugins-mu/siemens-wp-cli/inc/namespace.php?q=migrate+ppa#L386) we used the last time we did this ).

So I'd like to see a more targeted query unless there is some context for not doing so.

2022-06-13 07:53 UTC, shadyvb commented on README.md
> +Authorship implements a custom flag for use with posts, and a migration command for PublishPress Authors.
Probably don't need to mention PPA directly here, since the migration command can expand in the future.

2022-06-13 07:53 UTC, shadyvb commented on inc/cli/class-commands.php
> +		WP_CLI::log( 'To perform this migration you may need to activate the publishpress authors plugin' );
It'd be nice if we don't require the plugin to be activated, if the only reason is the taxo definition, we can always register it on the spot to make the query work.

2022-06-13 07:53 UTC, shadyvb commented on inc/cli/class-commands.php
> +			}
Nice one! Taking it one step further to set the default inline as well.

```php
$dry_run = filter_var( $assoc_args['dry-run'] ?? true, FILTER_VALIDATE_BOOLEAN ); // default is true
```

2022-06-15 15:02 UTC, tomjn commented
> Running time can be drastically improved if we did the filtering in the query rather than after. ( and even substantially faster if we went lower level as in the [original command](https://cs.github.com/humanmade/siemens-ingenuity/blob/154b8d6477ececb5336aeed71a72c51a68a30142/content/plugins-mu/siemens-wp-cli/inc/namespace.php?q=migrate+ppa#L386) we used the last time we did this ).

@shadyvb party of the reason was to simplify things, as a one time operation this isn't something that would run at regular intervals so I prioritised legibility and simplicity. The original command did things that weren't clear, which left us in an awkward position when we had to fix it. I'd also like to avoid running post meta queries if possible, or the question of posts being missed. Registering a taxonomy with the same name is a good shout out though

2022-06-16 10:23 UTC, shadyvb reviewed
@tomjn Can we add a filter for the query for large installation that'd not want to process each post individually, eg to use meta queries and elasticsearch, and document that in the docs ?

Otherwise, looks good!

2022-06-16 10:55 UTC, johnbillion requested changes
Just some minor feedback :)

2022-06-16 10:55 UTC, johnbillion commented on inc/cli/class-migrate-command.php
> +					WP_CLI::error( 'There was an error fetching the Publishpress Author data, is the plugin activated?', false );
```suggestion
					WP_CLI::error( 'There was an error fetching the PublishPress Author data, is the plugin activated?', false );
```

2022-06-16 10:55 UTC, johnbillion commented on inc/cli/class-migrate-command.php
> +				 * We're going to loop through all the Publishpress authors,
```suggestion
				 * We're going to loop through all the PublishPress authors,
```

2022-06-16 10:55 UTC, johnbillion commented on inc/cli/class-migrate-command.php
> +		if ( ! is_plugin_active( 'publishpress-authors/publishpress-authors.php' ) ) {
```suggestion
		if ( ! taxonomy_exists( 'author' ) ) {
```

This is a bit more specific and means it'll still work if for example PPA is installed as a mu-plugin.

2022-06-16 15:05 UTC, tomjn commented
@shadyvb I've added a `tax_query` to filter to just posts with terms in the `author` taxonomy, do you think that'll be enough?

2022-06-16 15:19 UTC, shadyvb commented
That's good, but an additional filter for any arbitrary changes might also be useful, however not required, since people can still filter the query using native hooks anyways.

Happy for this to go as is.

2022-06-16 15:19 UTC, shadyvb approved these changes

2022-06-17 09:46 UTC, merged