Update to use capabilities queries
humanmade/authorship pull request #93
Opened 2022-03-07 05:59 UTC by robindevitt

WP 5.9 includes new capabilities user queries that replace the role based `who` query parameter. 

This PR includes the `capabilities` query.

[Issue #523](https://github.com/humanmade/altis-cms/issues/523)

2022-03-07 06:07 UTC, robindevitt commented
I have noticed that all the checks have failed. Should I review each and fix appropriately? From what I have seen they don't appear to be directly related to the code changes made, a few are falling at "Install PHP Dependencies".

2022-03-07 08:40 UTC, shadyvb requested changes
The changes seem fine, apart from lock files. 

- I can see composer lock file includes more changes that might not be needed ( eg: coding standards version update ), so wondering how the WordPress update was carried out.
- Is the packages lock file update expected ? seems like quite a bit of changes.

Also, do we need to update the reference at https://github.com/humanmade/authorship/blob/develop/.github/workflows/test.yml#L17 ?

Also we do need to fix the CI before merging. I can see it's the composer version that might need to be updated.

2022-03-07 14:35 UTC, robindevitt commented
Hey @shadyvb 

Thanks for the review and direction ([slack thread](https://hmn.slack.com/archives/C5WSNGC9F/p1646641944706249)).

I have updated the PR.

I have [one check failing](https://github.com/humanmade/authorship/runs/5449820415?check_suite_focus=true), is this the same as what you referenced in your review earlier?

2022-03-10 07:34 UTC, shadyvb approved these changes

2022-03-10 11:10 UTC, merged